config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, foreign_key: 'group_id'
  has_many :users, through: :group_users
  has_many :messages
  # validates :name, presence: true, uniqueness: true


  def show_last_message
    if (last_message = messages.last).present?
      last_message.text? ? last_message.text : '画像が投稿されています'
    else
      'まだメッセージはありません'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group

  # validates :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :text, presence: true, unless: :image?
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :group_users, foreign_key: 'user_id'
  has_many :groups, through: :group_users
  has_many :messages

  validates :name, :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :create]
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      render :new
    end
  end

  def edit
    @group_users = @group.users
  end

  def update
     if @group.update(group_params)
       redirect_to group_messages_path(@group), notice: 'グループを編集しました'
     else
       render :edit
     end
  end

  private
  def group_params
    params.require(:group).permit(:name, { user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user).order("created_at ASC")

    respond_to do |format|
      format.html
      format.json { @new_message = Message.where('id > ? ', params[:id])}
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        # format.html {redirect_to group_messages_path(@group), notice: 'メッセージが送信されました'}
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id, name: nil).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path, notice: "ユーザ情報を更新しました"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/massages_helper.rb
module MassagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_chat-main.html.haml
.chat-main__header
  .chat-main__header--group.clearfix
    .chat-main__header--group-name
      = @group.name
    %ul
      %li.chat-main__header--group-edit-btn
        = link_to 'edit', "/groups/#{@group.id}/edit", method: :get
  .chat-main__header-members
    MEMBER:
    - @group.users.each do |user|
      = user.name




    / %form#new_message.chat-main__footer-form{"accept-charset" => "UTF-8", :action => "/groups/362/messages", :enctype => "multipart/form-data", :method => "post"}
    /   %input{:name => "utf8", :type => "hidden", :value => "✓"}/
    /   %input{:name => "authenticity_token", :type => "hidden", :value => "irkWRuBh5bdyIkyYvQXQwoYxYRiTpVl4Yu2XO8z8MlRjoPlGf+fZNjx8/2kwqAGRg5gvEsffTYp1m8EjU82aIg=="}/
    /   .chat-main__footer-body
    /     %input#message_body.message{:name => "message[body]", :placeholder => "type a message", :type => "text"}/
    /     %label.chat-file{:for => "message_image"}
    /       %input#message_image.image{:name => "message[image]", :type => "file"}/
    /       %i.fa.fa-image
    /   %input.submit{"data-disable-with" => "Send", :name => "commit", :type => "submit", :value => "Send"}/

app/views/groups/_chat-side.html.haml
.chat-side
  .chat-side__user
    .header
      %h3.header__user-name
        = current_user.name
      %ul.header__user--lists
        %li.list
          = link_to new_group_path do
            = fa_icon 'pencil-square-o', class: 'icon'
        %li.list
          = link_to edit_user_path(:user) do

            = fa_icon 'cog', class: 'icon'
  .chat-side__groups
    .chat-side__groups-list
      - current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          .chat-side__group
            .chat-side__group-name
              = group.name
            .chat-side__group-message
              = group.show_last_message

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat_group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバーを追加, class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.text_field :name, name: 'keyword', class: 'chat-group-form__input', id: 'user-search-field', placeholder: '追加したいユーザー名を入力してください', value: ""
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: 'chat-group-form__label'

    .chat-group-form__field--right
      #chat-group-users
        - group.users.each.with_index do |user, i|
          .chat-group-user.clearfix{id: "chat-group-user-#{i}"}
          = f.hidden_field :user_ids, multiple: true, value: "#{user.id}"
          #chat-group-user.chat-group-user.remove-from-list.clearfix
            %p.chat-group-user__name
              = user.name
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn#delete-user-button 削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.notification
  .notice

= render 'groups/chat-side'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag(:div, value, class: "flash flash__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .notification
      .notice
    = render 'layouts/flash'
    = yield

app/views/massages/index.html.haml
.notification
  .notice
.chat-side
  .chat-side__user
    .chat-side__user-content
      .chat-side__user-name seo
      %a{href: '/groups/new', class: "chat-side__user--new--group"}
        %i.fa.fa-pencil-square-o
          ::before
      %a{href: '/users/edit', class: "chat-side__user--edit-user"}
        %i.fa.fa-fa-cog
          ::before
  .chat-side__groups
    .chat-side__groupes-list
      %a{href: ''}
        .chat-side__group
          .chat-side__group-name
            sample
          .chat-side__group-message
            = @messages
.chat-main
  .chat-main__header
    .chat-main__header--group.clearfix
      .chat-main__header--group-name
        sample
      %a.chat-main__header--group-edit-btn{href: ''}
        edit
        ::after
      .chat-main__header-members
      "MEMBER:"
      %i
      James
  .chat-main__body
    .chat-main__body--messages-list
      .chat-main__message.clearfix{data: {id: '1'}}
        .chat-main__message-name
        James
        .chat-main__message-time
        2017/12/27 14:38:57
        .chat-main__message-body
        = @messages
        ::after
      .chat-main__message.clearfix{data: {id: '2'}}
        .chat-main__message-name
        James
        .chat-main__message-time
        2017/12/27 14:38:57
        .chat-main__message-body
        @messages
        ::after
  .chat-main__footer
    %form#new_message.chat-main__footer-form{ enctype: 'multipart/form-data', action: '/groups/1/messages', accept-charset="UTF-8", method: :post }
      %input

app/views/messages/_footer.html.haml
.chat-main__footer-form
  = form_for [@group, @message] do |f|
    .chat-main__footer-body
      = f.text_field :text, class: 'message', placeholder: 'type a message'
      = f.label :image, class: 'chat-file' do
        = fa_icon 'picture-o', class: 'icon'
        = f.file_field :image, class: 'image'
    = f.submit 'Send', class: 'submit', id: "send_button"

app/views/messages/_message.html.haml
.chat-main__message.clearfix{"data-message-id": message.id}
  .chat-main__message-name
    = message.user.name
  .chat-main__message-time
    = message.created_at.strftime("%Y-%m-%d %H:%M:%S")
  .chat-main__message-body
    - if message.text.present?
      %p.chat-main__message-text
        = message.text
      .chat-main__message-image
    = image_tag message.image.url if message.image.present?

app/views/messages/index.html.haml
.notification
  .notice

= render 'groups/chat-side'

.chat-main
  = render 'groups/chat-main'
  .chat-main__body
    = render partial: 'message', collection: @messages
  .chat-main__footer
    = render 'messages/footer'

app/views/messages/show.html.haml
.notification
  .notice

= render 'groups/chat-side'

= render 'groups/chat-main'

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'